#!/usr/bin/env python3
"""
embed_assets.py — Regenerate src/web_assets.h from data/ source files.

Usage:
    python3 scripts/embed_assets.py

Run this script after editing any file under data/ and before flashing.
It reads data/index.html, data/style.css, and data/app.js, then writes
src/web_assets.h with the updated PROGMEM raw-string literals.
"""

import pathlib
import sys

ROOT     = pathlib.Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
OUT_FILE = ROOT / "src" / "web_assets.h"

ASSETS = [
    ("index_html", DATA_DIR / "index.html", "text/html"),
    ("style_css",  DATA_DIR / "style.css",  "text/css"),
    ("app_js",     DATA_DIR / "app.js",     "application/javascript"),
]

HEADER = '''\
/**
 * @file  web_assets.h
 * @brief Web dashboard assets stored in ESP8266 flash (PROGMEM).
 *
 * AUTO-GENERATED by scripts/embed_assets.py — do not edit by hand.
 * Edit files in data/ and re-run the script.
 */

#pragma once
#include <pgmspace.h>

'''

def embed(var_name: str, path: pathlib.Path) -> str:
    content = path.read_text(encoding="utf-8")
    # Escape the )rawliteral delimiter if it appears in content (extremely unlikely)
    if ")rawliteral" in content:
        raise ValueError(f"{path}: content contains ')rawliteral' — choose a different delimiter")
    return (
        f"// ── {path.name} {'─' * (52 - len(path.name))}\n"
        f"const char {var_name}[] PROGMEM = R\"rawliteral(\n"
        f"{content}\n"
        f")rawliteral\";\n\n"
    )

def main() -> int:
    missing = [p for _, p, _ in ASSETS if not p.exists()]
    if missing:
        for p in missing:
            print(f"ERROR: missing asset: {p}", file=sys.stderr)
        return 1

    out = HEADER
    for var, path, _ in ASSETS:
        print(f"  embedding {path.relative_to(ROOT)} → {var}")
        out += embed(var, path)

    OUT_FILE.write_text(out, encoding="utf-8")
    print(f"\nWritten: {OUT_FILE.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
